name: 'Package version bump and tag|commit'
description: 'Read version from package file, bump it, and create tag, commit'

inputs:
  lang:
    description: 'Who to greet'
    required: true
    default: 'js'
  bumpLvl:
    description: 'Bump level major, minor, patch, hotfix'
    required: true
    default: 'patch'
  save:
    description: 'You pass to true to save package file, tag and commit'
    required: false
    default: 'false'
  githubToken:
    description: 'Github token ${{ secrets.SV_GITHUB_ACTIONS }}'
    required: false
  path:
    description: 'Path to package file '
    required: false

outputs:
  version:
    description: 'The bumped version of the package'

runs:
  using: 'node20'
  main: 'dist/index.js'
